import { NormalizationCategories } from './interfaces';

export const DEFAULT_METRICS = [
    {
        id: 0,
        columnName: 'lead_time_portfolio_85',
        displayName: 'Lead Time Portfolio Level Items',
        metric_description: '(85th percentile)',
        isBenchmarkingRecommended: false,
        description: '',
        value: '',
        unit: '',
    },
    {
        id: 1,
        columnName: 'lead_time_portfolio_avg',
        displayName: 'Lead Time Portfolio Level Items',
        metric_description: '(Average)',
        isBenchmarkingRecommended: false,
        description: '',
        value: '',
        unit: '',
    },
    {
        id: 2,
        columnName: 'lead_time_target_met',
        displayName: 'Lead Time Team Level Items',
        metric_description: '(85th percentile)',
        isBenchmarkingRecommended: true,
        description: 'max of',
        value: 7,
        unit: 'days',
    },
    {
        id: 3,
        columnName: 'lead_time_team_avg',
        displayName: 'Lead Time Team Level Items',
        metric_description: '(Average)',
        isBenchmarkingRecommended: true,
        description: 'max of',
        value: 8,
        unit: 'days',
    },
    {
        id: 4,
        columnName: 'fitness_level',
        displayName: 'Fitness Level',
        isBenchmarkingRecommended: true,
        description: 'min',
        value: 85,
        unit: '%',
    },
    {
        id: 5,
        columnName: 'wip_count',
        displayName: 'WIP Count',
        isBenchmarkingRecommended: false,
        description: 'max of',
        value: 4,
        unit: 'flow items',
    },
    {
        id: 6,
        columnName: 'wip_age_85',
        displayName: 'WIP age',
        metric_description: '(85th percentile)',
        isBenchmarkingRecommended: false,
        description: '',
        value: '',
        unit: '',
    },
    {
        id: 7,
        columnName: 'wip_age_avg',
        displayName: 'WIP age',
        metric_description: '(Average)',
        isBenchmarkingRecommended: false,
        description: '',
        value: '',
        unit: '',
    },
    {
        id: 8,
        columnName: 'total_throughput',
        displayName: 'Throughput',
        isBenchmarkingRecommended: false,
        description: '',
        value: '',
        unit: '',
    },
    {
        id: 9,
        columnName: 'flow_efficiency',
        displayName: 'Flow Efficiency',
        isBenchmarkingRecommended: true,
        description: 'min of',
        value: 40,
        unit: '%',
    },
    {
        id: 10,
        columnName: 'flow_debt',
        displayName: 'Flow Debt',
        isBenchmarkingRecommended: true,
        description: '',
        value: '',
        unit: '',
    },
];

export const fixedNormalizationCategoriesDisplayNameRecord = {
    [NormalizationCategories.DEMAND]: 'Demand',
    [NormalizationCategories.VALUE_AREA]: 'Value Area',
    [NormalizationCategories.QUALITY]: 'Class of Value',
    [NormalizationCategories.PLANNED_UNPLANNED]: 'Planned/Unplanned',
    [NormalizationCategories.REFUTABLE_IRREFUTABLE]: 'Refutable/Irrefutable',
    [NormalizationCategories.DELAYABLE_NONDELAYABLE]: 'Delayable/Non-Delayable',
    [NormalizationCategories.CLASS_OF_SERVICE]: 'Class of Service',
};

export const mapOfCategoriesDisplayName: { [key: string]: string } = {
    demand: 'Demand',
    'value-area': 'Value Area',
    quality: 'Class of Value',
    'planned-unplanned': 'Planned/Unplanned',
    'refutable-irrefutable': 'Refutable/Irrefutable',
    'delayable-non-delayable': 'Delayable/Non-Delayable',
    'class-of-service': 'Class of Service',
};
